apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-api-ingress
  namespace: davyjones-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.davyjones.cloud
    secretName: api-tls
  rules:
  - host: api.davyjones.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: central-api
            port:
              number: 80
